Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Controllers/BusinessController/ReportsController.cs
using Big.MeadJohnson.Business.Business;
using Big.MeadJohnson.Business.Enums;
using Big.MeadJohnson.Business.Models;
using Big.MeadJohnson.Business.ViewModel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Big.MeadJohnson.CRM.UI.Controllers.BusinessController
{
    [Authorize(Roles = "Súper_Administrador")]
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {

            GeneralReportViewModel model = new GeneralReportViewModel();

            var professionalType = ProfessionalBLL.GetAllProfessionalTypes();
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = new List<City>();
            var users = new List<User>();

            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", model.DepartamentId);
            ViewBag.CityId = new SelectList(cities, "Id", "Name", model.CityId);
            ViewBag.ProfessionalTypeId = new SelectList(professionalType, "Id", "Name", model.ProfessionalTypeId);
            ViewBag.MsrId = new SelectList(users, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(GeneralReportViewModel model)
        {
            if (model.DepartamentId == 0)
                model.DepartamentId = null;

            if (model.CityId == 0)
                model.CityId = null;

            if (model.MsrId == 0)
                model.MsrId = null;

            if (model.ProfessionalTypeId == 0)
                model.ProfessionalTypeId = null;

            var report = Business.Reports.GeneralReport.GetGeneralReport(model.DepartamentId, model.CityId, model.MsrId, model.ProfessionalTypeId);

            if (report == null)
                ModelState.AddModelError(string.Empty, "No se encontraron registros que coincidan con los criterios de búsqueda.");
            else
            {
                ModelState.AddModelError(string.Empty, "El reporte se esta generando.");
                ExportToExcel(report);
            }


            var professionalType = ProfessionalBLL.GetAllProfessionalTypes();
            var departaments = DepartamentBLL.GetAllDepartaments();

            var cities = new List<City>();
            var users = new List<User>();

            if (model.CityId != null && model.CityId != 0)
            {
                cities = CityBLL.GetCitiesByDepartamentId((int)model.DepartamentId);
                users = UserBLL.GetAUserByCityId((int)model.CityId).Where(u => u.ProfileId == (int)EnumProfile.representantes).ToList();
            }

            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", model.DepartamentId);
            ViewBag.CityId = new SelectList(cities, "Id", "Name", model.CityId);
            ViewBag.ProfessionalTypeId = new SelectList(professionalType, "Id", "Name", model.ProfessionalTypeId);
            ViewBag.MsrId = new SelectList(users, "Id", "Name", model.MsrId);

            return View(model);
        }


        public void ExportToExcel<T>(List<T> list)
        {

            var grid = new GridView();
            grid.DataSource = list;
            grid.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=MyExcelFile.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);

            grid.RenderControl(htw);

            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
        }
    }
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Controllers/BusinessController/UsersController.cs
namespace Big.MeadJohnson.CRM.UI.Controllers.BusinessController
{
    using System.Linq;
    using System.Threading.Tasks;
    using System.Net;
    using System.Web.Mvc;
    using Big.MeadJohnson.Core.DAL;
    using Big.MeadJohnson.Business.Business;
    using System.Collections.Generic;
    using Big.MeadJohnson.Business.Enums;
    using System;
    using Big.MeadJohnson.Business.ViewModel;
    using Microsoft.AspNet.Identity;
    using Big.MeadJohnson.Business.Models;

    
    public class UsersController : Controller
    {
        private dbBigMeadJohnson db = new dbBigMeadJohnson();

        [Authorize(Roles = "Súper_Administrador")]
        public async Task<ActionResult> Index()
        {
            var profiles = ProfileBLL.GetAllProfiles();
            var users = await UserBLL.GetAllUser();

            foreach (var user in users)
            {
                user.Profilename = profiles.Where(p => p.Id == user.ProfileId).FirstOrDefault().Description;
            }

            return View(users);
        }

        [Authorize(Roles = "Súper_Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = UserBLL.GetUserById((int)id);
            return View(user);
        }

        [Authorize(Roles = "Súper_Administrador")]
        public ActionResult Create()
        {
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = new List<Business.Models.City>();
            var profiles = ProfileBLL.GetAllProfiles();
            var managers = ManagerBLL.GetAllManagers();

            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name");
            ViewBag.CityId = new SelectList(cities, "Id", "Name");
            ViewBag.ProfileId = new SelectList(profiles, "Id", "Description");
            ViewBag.ManagerId = new SelectList(managers, "Id", "Names");
            User user = new User { Guid = Guid.NewGuid() };

            return View(user);
        }

        [Authorize(Roles = "Súper_Administrador")]
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create(Business.Models.User user)
        {
            var response = new Response<bool>();
            var profiles = ProfileBLL.GetAllProfiles();

            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = CityBLL.GetCitiesByDepartamentId(departaments.FirstOrDefault().Id);
            var managers = ManagerBLL.GetAllManagers();

            ViewBag.CityId = new SelectList(cities, "Id", "Name", user.CityId);
            ViewBag.ProfileId = new SelectList(profiles, "Id", "Description", user.ProfileId);
            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", user.DepartamentId);
            ViewBag.ManagerId = new SelectList(managers, "Id", "Names", user.ManagerId);

            if (user.ProfileId == (int)EnumProfile.representantes && (user.CityId == null || user.CityId == 0))
            {
                ModelState.AddModelError(string.Empty, "Debe seleccionar un departamento y una ciudad");
            }

            var objUser = UserBLL.GetUserByUserName(user.UserName);
            if (objUser != null)
            {
                ModelState.AddModelError("UserName", "El nombre de usuario ya se encuentra registrado.");
            }
            else
            {

                objUser = UserBLL.GetUserByEmail(user.Email);
                if (objUser != null)
                    ModelState.AddModelError("Email", "El correo ya se encuentra registrado.");

                //if (user.ManagerId == 0 || user.ManagerId == null)
                //    ModelState.AddModelError("ManagerId", "Debe seleccionar un gerente");

                if (user.ProfileId == 0 || user.ProfileId == null)
                    ModelState.AddModelError("ProfileId", "Debe seleccionar un perfil");
            }

            user.Guid = Guid.NewGuid();
            user.RegisterDate = DateTime.Now;
            user.IsFirstUse = true;

            if (ModelState.IsValid)
            {
                var result = UserBLL.SaveNewUser(user);
                if (result)
                {

                    Helper.UserHelper.CreateUserASP(
                        user.Email,
                        user.UserName,
                        profiles.Where(p => p.Id == user.ProfileId).FirstOrDefault().Description,
                        user.Password);

                    response = new Response<bool>()
                    {
                        Result = true,
                        Model = result,
                        Message = "El usuario ha sido creado con éxito.",
                        Title = "Usuarios"
                    };

                    return Json(response);
                }
            }

            response = new Response<bool>()
            {
                Result = false,
                Model = false,
                Message = getModelError(ModelState.Values),
                Title = "Usuarios"
            };



            return Json(response);
            //return View(user);
        }

        [Authorize(Roles = "Súper_Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = UserBLL.GetUserById((int)id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var departaments = DepartamentBLL.GetAllDepartaments();
            var city = new Business.Models.City();
            var departament = new Business.Models.Departament();
            var managers = ManagerBLL.GetAllManagers();

            if (user.CityId != null)
            {
                city = CityBLL.GetCityById((int)user.CityId);
                departament = departaments.Where(d => d.Id == city.DepartamentId).FirstOrDefault();
            }

            var cities = CityBLL.GetCitiesByDepartamentId(departament != null ? departament.Id : departaments.FirstOrDefault().Id);

            var profiles = ProfileBLL.GetAllProfiles();
            ViewBag.ProfileId = new SelectList(profiles, "Id", "Description", user.ProfileId);
            ViewBag.CityId = new SelectList(cities, "Id", "Name", user.CityId != null ? user.CityId : null);
            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", city?.DepartamentId);
            ViewBag.ManagerId = new SelectList(managers, "Id", "Names", user.ManagerId);
            return View(user);
        }

        [Authorize(Roles = "Súper_Administrador")]
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            var response = new Response<bool>();
            var profiles = ProfileBLL.GetAllProfiles();
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = CityBLL.GetCitiesByDepartamentId(departaments.FirstOrDefault().Id);
            var managers = ManagerBLL.GetAllManagers();
            ViewBag.CityId = new SelectList(cities, "Id", "Name", user.CityId);
            ViewBag.ProfileId = new SelectList(profiles, "Id", "Description", user.ProfileId);
            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", user.DepartamentId);
            ViewBag.ManagerId = new SelectList(managers, "Id", "Names", user.ManagerId);

            if (user.ProfileId == (int)EnumProfile.representantes && (user.CityId == null || user.CityId == 0))
            {
                ModelState.AddModelError(string.Empty, "Debe seleccionar un departamento y una ciudad");
                return View(user);
            }

            var oldUser = UserBLL.GetUserById(user.Id);
            if (oldUser != null)
            {
                if (oldUser.ProfileId != user.ProfileId)
                    Helper.UserHelper.UpdateUserRole(
                        user.UserName,
                        profiles.Where(p => p.Id == user.ProfileId).FirstOrDefault().Description,
                        profiles.Where(p => p.Id == oldUser.ProfileId).FirstOrDefault().Description);

                if (oldUser.Password != user.Password)
                    Helper.UserHelper.ChangePassword(user.UserName, oldUser.Password, user.Password);


                if (user.Email != oldUser.Email)
                    Helper.UserHelper.UpdateUserMail(user.Email, user.UserName);

                user.RegisterDate = oldUser.RegisterDate;
                user.IsFirstUse = oldUser.IsFirstUse;
            }

            if (user.IsActive == true && oldUser.IsActive == false)
            {
                Helper.UserHelper.RemoveUserRole(
                   user.UserName,
                   profiles.Where(p => p.Id == oldUser.ProfileId).FirstOrDefault().Description);

                Helper.UserHelper.SaveUserRole(
                    user.UserName,
                    profiles.Where(p => p.Id == user.ProfileId).FirstOrDefault().Description);
            }

            if (!user.IsActive)
            {
                Helper.UserHelper.RemoveUserRole(
                  user.UserName,
                  profiles.Where(p => p.Id == user.ProfileId).FirstOrDefault().Description);
            }

            if (ModelState.IsValid)
            {
                var result = UserBLL.UpdateUser(user);

                if (result)
                {
                    response = new Response<bool>()
                    {
                        Result = true,
                        Model = result,
                        Message = "El usuario ha sido Actualizado con éxito.",
                        Title = "Usuarios"
                    };

                    return Json(response);
                }

            }

            response = new Response<bool>()
            {
                Result = false,

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/dataTables.responsive.css" rel="stylesheet" />

    <script src="@Url.Content("~/Scripts/jquery.quicksearch.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/canvasSecretary.js")" type="text/javascript"></script>

    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':

                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],

                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =

                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);

        })(window, document, 'script', 'dataLayer', 'GTM-NQTXNNN');
    </script>
    <!-- End Google Tag Manager -->
</head>
<body background="~/Content/img/Background-2.jpg">
    @using Microsoft.AspNet.Identity
    <!-- Google Tag Manager (noscript) -->

    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NQTXNNN"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>

    <!-- End Google Tag Manager (noscript) -->
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/img/logo-3.png" alt="Sample Image" style="height:55px; width:150px;" />
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    if (Big.MeadJohnson.Business.Business.UserBLL.GetUserByUserName(@User.Identity.GetUserName()).IsFirstUse == false)
                    {<ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Inicio", "Index", "Professionals")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profesionales<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    @if (User.IsInRole("Súper_Administrador"))
                                    {
                                        <li>@Html.ActionLink("Administrar Profesionales", "Index", "Professionals")</li>
                                    }

                                    @if (User.IsInRole("Representantes") || User.IsInRole("Administrador"))
                                    {
                                        <li>@Html.ActionLink("Gestión de Profesionales", "Index", "Professionals")</li>
                                    }
                                </ul>
                            </li>

                            @if (User.IsInRole("Súper_Administrador"))
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Usuarios", "Index", "Users")</li>
                                    </ul>
                                </li>

                            }

                            @if (User.IsInRole("Súper_Administrador") || User.IsInRole("Administrador"))
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Informe general", "Index", "Reports")</li>
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gerentes<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Gerentes", "Index", "Gerentes")</li>
                                    </ul>
                                </li>
                            }
                            @*@if (User.IsInRole("Súper_Administrador"))
                                {
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuración<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Configuraciones del sistema", "Index", "Home")</li>
                                        </ul>
                                    </li>
                                }*@

                        </ul>
                    }
                }

                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <!-- Modal -->

        <div class="modal fade" id="genericModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h2 class="modal-title" id="modalTitle"></h2>
                    </div>
                    <div class="modal-body">
                        <div class="te">
                            <p id="modalMessage"></p>
                        </div>
                        <div id="response" style="margin-top:20px;">
                            <button class="btn" data-dismiss="modal" aria-hidden="true">Aceptar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="genericConfirmEnable" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h2 class="modal-title" id="modalTitle">Activar / Inactivar Usuarios</h2>
                    </div>
                    <div class="modal-body">
                        <div class="te">
                            <p id="modalConfirmMessage"></p>
                        </div>
                        <div id="response" style="margin-top:20px;">
                            <button class="btn" id="btnAcept" data-dismiss="modal" aria-hidden="true">Aceptar</button>
                            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                        </div>
                        <div id="response" style="margin-top:20px;">

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer></footer>
    </div>
    <input type="hidden" id="hfUrlBase" value="@System.Configuration.ConfigurationManager.AppSettings["urlSite"]" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/jquery.listswap.js")" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script>
        $("#digitar").click(function () {
            $(this).css("display", "none");
            $('body').append("<div id='mascara' style='position: fixed;width: 100%;height: 100%;left: 0;top: 0;background: rgba(0,0,0,0.7);z-index: -1;'></div>");
            $('#canvas').appendTo('#mascara');
            $("#canvas").css({ "position": "fixed", "left": "50%", "top": "0", "transform": "translate(-50%, -50%)", "-webkit-transform": "translate(-50%, -50%)", "z-index": "10", "background": "#ffffff", "margin": "calc(50vh - 150px) auto 0" });
            //$('.container').css("opacity", "0");
            $(".tabbable").parent().css("display", "none");
            $("#limpiar").parent().appendTo("#mascara");
            $("#limpiar").parent().removeClass("col-md-offset-4");
            $("#limpiar").parent().css({ "position": "fixed", "left": "50%", "bottom": "30%", "transform": "translate(-50%, -50%)", "-webkit-transform": "translate(-50%, -50%)", "text-align": "center" });
            $("#canvas").css("display", "block !important");
        });

        $("#btnSaveCanvas").click(function () {
            $("#digitar").css("display", "block");
            $("#mascara").css("display", "none");
            $(".tabbable").parent().css("display", "block");
            $('#digitar').css("display", "block");



        });

    </script>
</body>
</html>