Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Controllers/BusinessController/GerentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Big.MeadJohnson.Business.Business;
using Big.MeadJohnson.Business.Models;
using Big.MeadJohnson.Core.DAL;
using PagedList;

namespace Big.MeadJohnson.CRM.UI.Controllers.BusinessController
{
    public class GerentesController : Controller
    {
        //private dbBigMeadJohnson db = new dbBigMeadJohnson();

        // GET: Gerentes
        public ActionResult Index(List<Gerente> view, int? page)
        {
            page = (page ?? 1);
            ViewBag.Creado = TempData["CreadoDetalle"];
            return View(GerenteBLL.GetAllGerentes().ToPagedList((int)page, 15));
        }

        // GET: Gerentes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gerente = GerenteBLL.ConsultarGerente(id);
            if (gerente == null)
            {
                return HttpNotFound();
            }
            return View(gerente);
        }

        // GET: Gerentes/Create
        public ActionResult Create()
        {
            ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
            ViewBag.CiudadId = new SelectList(CityDAL.GetAllCities(), "ID", "NAME");
            return View();
        }

        // POST: Gerentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NombreCompleto,Cedula,CorreoElectronico,CiudadId")] Gerente gerente)
        {
            Gerente existeXCedula = GerenteBLL.ConsultarGerenteXCedula(gerente.Cedula);
            if (existeXCedula != null)
            {
                ModelState.AddModelError("Cedula", "La cédula pertenece a " + existeXCedula.NombreCompleto);
            }

            Gerente existeXCorreo = GerenteBLL.ConsultarGerenteXCorreo(gerente.CorreoElectronico);
            if (existeXCorreo != null)
            {
                ModelState.AddModelError("CorreoElectronico", "El Correo existe para " + existeXCorreo.NombreCompleto);
            }

            if (ModelState.IsValid)
            {
                gerente.Activo = true;
                gerente.ID = Guid.NewGuid().ToString();
                GerenteBLL.CrearGerente(gerente);
                TempData["CreadoDetalle"] = "El gerente ha sido creado con éxito";
                return RedirectToAction("Index");
            }

            ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
            ViewBag.CiudadId = new SelectList(CityDAL.GetAllCities(), "ID", "NAME");
            return View(gerente);
        }

        // GET: Gerentes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gerente = GerenteBLL.ConsultarGerente(id);
            if (gerente == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
            return View(gerente);
        }

        // POST: Gerentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Gerente gerente)
        {
            Gerente existeXCedula = GerenteBLL.ConsultarGerenteXCedula(gerente.Cedula);
            if (gerente.ID.ToUpper() != existeXCedula.ID.ToUpper())
            {
                if (existeXCedula != null)
                {
                    if (gerente.ID != existeXCedula.ID)
                        ModelState.AddModelError("Cedula", "La cédula pertenece a " + existeXCedula.NombreCompleto);
                }
            }
            Gerente existeXCorreo = GerenteBLL.ConsultarGerenteXCorreo(gerente.CorreoElectronico);
            if (gerente.ID.ToUpper() != existeXCorreo.ID.ToUpper())
            {
                if (existeXCorreo != null)
                {
                    if (gerente.ID != existeXCorreo.ID)
                        ModelState.AddModelError("CorreoElectronico", "El Correo existe para " + existeXCorreo.NombreCompleto);
                }
            }                

            if (ModelState.IsValid)
            {
                var editado = GerenteBLL.EditarGerente(gerente);

                return RedirectToAction("Index");
            }
            ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
            return View(gerente);
        }

        // GET: Gerentes/Delete/5
        public ActionResult Delete(string id)
        {
            return View();
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Gerente gerente = db.Gerentes.Find(id);
            //if (gerente == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(gerente);
        }

        // POST: Gerentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            return RedirectToAction("Index");
            //Gerente gerente = db.Gerentes.Find(id);
            //db.Gerentes.Remove(gerente);
            //db.SaveChanges();
            //return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GetCitiesByDepartament(string departamentId)
        {
            int statId;
            List<SelectListItem> districtNames = new List<SelectListItem>();
            if (!string.IsNullOrEmpty(departamentId))
            {
                statId = Convert.ToInt32(departamentId);
                List<City> districts = CityBLL.GetCitiesByDepartamentId(statId).ToList();
                districts.ForEach(x =>
                {
                    districtNames.Add(new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
                });
            }
            return Json(districtNames, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddCities(string id)
        {
            ViewBag.GERENTE_ID = new SelectList(GerenteDAL.GetAllGerentes().Where(x => x.ID.ToString() == id), "ID", "NOMBRE_COMPLETO", id);
            ViewBag.IDGerente = id;
            ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
            ViewBag.CITY_ID = new SelectList(CityDAL.GetAllCities(), "GUID", "NAME");
            return View();
        }

        [HttpPost]
        public ActionResult AddCities(MJ_GERENTES_CITIES gerenCities)
        {
            try
            {
                var rta = GerenteBLL.AsociarCiudad(gerenCities);
                if (rta == "OK")
                {
                    TempData["CreadoDetalle"] = "Se ha agregado una ciudad correctamente al gerente";
                    return RedirectToAction("Index");
                }

                else
                {
                    ViewBag.GERENTE_ID = new SelectList(GerenteDAL.GetAllGerentes().Where(x => x.ID == gerenCities.GERENTE_ID), "ID", "NOMBRE_COMPLETO", gerenCities.GERENTE_ID);
                    ViewBag.DepartamentId = new SelectList(DepartamentDAL.GetAllDepartaments(), "ID", "NAME");
                    ViewBag.CITY_ID = new SelectList(CityDAL.GetAllCities(), "ID", "NAME");
                    return View();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/AddCities.cshtml
@model Big.MeadJohnson.Core.DAL.MJ_GERENTES_CITIES

@{
    ViewBag.Title = "AddCities";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">


    <h4>Asociar Ciudad a Gerente</h4>
    <hr />

    <div class="form-group">
        <label class="control-label col-md-2">Gerente</label> @*@Html.LabelFor(model => model.GERENTE_ID, "GERENTE_ID", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("GERENTE_ID", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.GERENTE_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Ciudad</label> @*@Html.LabelFor(model => model.CITY_ID, "CITY_ID", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("CITY_ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CITY_ID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Asociar" class="btn btn-default" />
        </div>
    </div>
    @Html.ActionLink("Volver", "Edit", new { id = ViewBag.IDGerente.ToString() })
</div>
}

<div>
    @Html.ActionLink("Listar Gerentes", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/Create.cshtml
@model Big.MeadJohnson.Business.Models.Gerente
@{
    ViewBag.Title = "Create";
}

<h2>Crear Gerente</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })*
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreCompleto, htmlAttributes: new { @class = "control-label col-md-2" })*
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreCompleto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreCompleto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })*
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Departamento</label>*
            <div class="col-md-10">
                @Html.DropDownList("DepartamentId", (SelectList)ViewBag.DepartamentId, "--Seleccione--", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadId, "CiudadId", htmlAttributes: new { @class = "control-label col-md-2" })*
            <div class="col-md-10">
                @Html.DropDownList("CiudadId", (SelectList)ViewBag.CiudadId, "--Seleccione--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CiudadId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Gerente" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listar Gerentes", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">
            var idDepartament = 'DepartamentId';
            var idCity = '@Html.IdFor(m => m.CiudadId)'
        $(document).ready(function () {
            $('#' + idDepartament).change(function () {
                $.ajax({
                    type: "post",
                    url: '@Html.Raw(Url.Action("GetCitiesByDepartament","Gerentes"))',
                    data: { departamentId: $('#' + idDepartament).val() },
                    datatype: "json",
                    traditional: true,
                    success: function (data) {
                        var district = "";
                        district = district + '<option value="">--Seleccionar--</option>';
                        for (var i = 0; i < data.length; i++) {
                            district = district + '<option value=' + data[i].Value + '>' + data[i].Text + '</option>';
                        }
                        district = district + '</select>';
                        $('#' + idCity).html(district);
                    }
                });
            });
        });
        </script>
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/Delete.cshtml
@model Big.MeadJohnson.Business.Models.Gerente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gerente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/Details.cshtml
@model Big.MeadJohnson.Business.Models.Gerente

@{
    /**/

    ViewBag.Title = "Details";
}

<h2>Detalle</h2>

<div>
    <h4>Gerente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

    </dl>
</div>
@if (Model.Ciudades.Count > 0)
{
    <div class="row">
        <b><p>Ciudad Asiganada</p></b>
        @foreach(var c in Model.Ciudades)
        {
            <p>@Html.Raw(c.Name)</p>
        }
    </div>
}

<p>
    @Html.ActionLink("Editar Gerente", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Listar Gerentes", "Index")
</p>

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/Edit.cshtml
@model Big.MeadJohnson.Business.Models.Gerente

@{
    ViewBag.Title = "Edit";
}
<style>
    .dual-list .list-group {
        margin-top: 8px;
    }

    .list-left li, .list-right li {
        cursor: pointer;
    }

    .list-arrows {
        padding-top: 100px;
    }

        .list-arrows button {
            margin-bottom: 20px;
        }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Modificar Gerente</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.NombreCompleto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NombreCompleto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreCompleto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (!string.IsNullOrEmpty(Model.Cedula))
            {
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            }
            else
            {
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
            }

            @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control", @onclick="el();" } })
            @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">        
        <div class="">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 checkbox">
                @Html.EditorFor(model => model.Activo)
            </div>
            @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
    <div class="container">
        <br />
        <div class="row">
            <div class="dual-list list-left col-md-5">
                <b>Ciudades Actuales</b>
                <div class="well text-right">
                    @Html.ActionLink("Asociar Otra Ciudad", "AddCities", new { id = Model.ID })
                    @*<div class="row">
                            <div class="col-md-10">
                                <div class="input-group">
                                    <span class="input-group-addon glyphicon glyphicon-search"></span>
                                    <input type="text" name="SearchDualList" class="form-control" placeholder="search" />
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="btn-group">
                                    <a class="btn btn-default selector" title="select all"><i class="glyphicon glyphicon-unchecked"></i></a>
                                </div>
                            </div>
                        </div>*@
                    <ul class="list-group">
                        @foreach (var c in Model.Ciudades)
                        {
                            <li class="list-group-item">@Html.Raw(c.Name)</li>
                        }
                    </ul>
                </div>
            </div>
            @*<div class="list-arrows col-md-1 text-center">
                    <button type="button" class="btn btn-default btn-sm move-left">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </button>
                    <button type="button" class="btn btn-default btn-sm move-right">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </button>
                </div>*@
            @*<div class="dual-list list-right col-md-5">
                    @Html.ActionLink("Agregar Ciudad", "AddCities", new { id = Model.ID })
                    <b>Ciudades Disponibles</b>
                    <div class="row">
                        <label class="control-label col-md-2">Departamento</label>*
                        <div class="col-md-10">
                            @Html.DropDownList("DepartamentId", (SelectList)ViewBag.DepartamentId, "--Seleccione--", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="well">

                        <div class="row">
                            <div class="col-md-2">
                                <div class="btn-group">
                                    <a class="btn btn-default selector" title="select all"><i class="glyphicon glyphicon-unchecked"></i></a>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <input type="text" name="SearchDualList" class="form-control" placeholder="search" />
                                    <span class="input-group-addon glyphicon glyphicon-search"></span>
                                </div>
                            </div>
                        </div>

                        <ul class="list-group" id="CiudadesNuevas">
                            <li class="list-group-item">Seleccione un Departamento</li>
                        </ul>
                    </div>
                </div>*@
        </div>
    </div>
</div>
}

    <div>
        @Html.ActionLink("Listar Gerentes", "Index", null, new { @class = "btn btn-warning" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var IdActivo = '@Html.IdFor(m => m.Activo)';
        var el = function () {            
            $('#' + IdActivo).val(!$('#' + IdActivo).val());
        }
    </script>
    @*<script type="text/javascript">
        var idDepartament = 'DepartamentId';
        var idCity = 'CiudadesNuevas'
        $(document).ready(function () {
            $('#' + idDepartament).change(function () {
                $.ajax({
                    type: "post",
                    url: '@Html.Raw(Url.Action("GetCitiesByDepartament","Gerentes"))',
                    data: { departamentId: $('#' + idDepartament).val() },
                    datatype: "json",
                    traditional: true,
                    success: function (data) {
                        var district = "";
                        for (var i = 0; i < data.length; i++) {
                            district = district + '<li class="list-group-item">' + data[i].Text + '</li>';
                        }
                        $('#' + idCity).html(district);
                    }
                });
            });
        });
    </script>*@

    @*<script>
        $(function () {

            $('body').on('click', '.list-group .list-group-item', function () {
                $(this).toggleClass('active');
            });
            $('.list-arrows button').click(function () {
                var $button = $(this), actives = '';
                if ($button.hasClass('move-left')) {
                    actives = $('.list-right ul li.active');
                    actives.clone().appendTo('.list-left ul');
                    actives.remove();
                } else if ($button.hasClass('move-right')) {
                    actives = $('.list-left ul li.active');
                    actives.clone().appendTo('.list-right ul');
                    actives.remove();
                }
            });
            $('.dual-list .selector').click(function () {
                var $checkBox = $(this);
                if (!$checkBox.hasClass('selected')) {
                    $checkBox.addClass('selected').closest('.well').find('ul li:not(.active)').addClass('active');
                    $checkBox.children('i').removeClass('glyphicon-unchecked').addClass('glyphicon-check');
                } else {
                    $checkBox.removeClass('selected').closest('.well').find('ul li.active').removeClass('active');
                    $checkBox.children('i').removeClass('glyphicon-check').addClass('glyphicon-unchecked');
                }
            });
            $('[name="SearchDualList"]').keyup(function (e) {
                var code = e.keyCode || e.which;
                if (code == '9') return;
                if (code == '27') $(this).val(null);
                var $rows = $(this).closest('.dual-list').find('.list-group li');
                var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
                $rows.show().filter(function () {
                    var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
                    return !~text.indexOf(val);
                }).hide();
            });

        });
    </script>*@
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Gerentes/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<Big.MeadJohnson.Business.Models.Gerente>

@{
    ViewBag.Title = "Index";
}

<h2>Gerentes</h2>

<p>
    @Html.ActionLink("Nuevo Gerente", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().NombreCompleto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CorreoElectronico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Activo)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>

                @Html.ActionLink("Consultar", "Edit", new { id = item.ID }, new { @class = "btn btn-info glyphicon glyphicon-edit " })
                @*@Html.ActionLink("Ver", "Details", new { id=item.ID }, new { @class = "btn btn-success glyphicon glyphicon-edit " }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id=item.ID }, new { @class = "btn btn-danger glyphicon glyphicon-edit " })*@
            </td>
        </tr>
    }
</table>
Página: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber), de: @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
PagedListRenderOptions.OnlyShowFivePagesAtATime);

@section scripts{
    @if (!string.IsNullOrEmpty(ViewBag.Creado))
    {
        <script>
            $('#modalTitle').html('Administración Gerentes');
            $('#modalMessage').html('@ViewBag.Creado');
            $('#genericModal').modal('show');
        </script>
    }

}