Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Controllers/BusinessController/ProfessionalsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Big.MeadJohnson.Business.Models;
using Big.MeadJohnson.Core.DAL;
using Big.MeadJohnson.Business.Business;
using Microsoft.AspNet.Identity;
using Big.MeadJohnson.Business.ViewModel;
using System.Linq;
using Big.MeadJohnson.Business.Enums;
using System.Transactions;
using System.Configuration;
using PagedList;
using Big.MeadJohnson.CRM.UI.Models;
using Big.MeadJohnson.Domain.Controller;
using Big.MeadJohnson.CRM.UI.Helper;

namespace Big.MeadJohnson.CRM.UI.Controllers.BusinessController
{
    // [Authorize(Roles = "Administrador,Representantes,Súper_Administrador")]
    public class ProfessionalsController : Controller
    {
        private DataContextLocal db = new DataContextLocal();

        [Authorize(Roles = "Súper_Administrador,Administrador,Representantes")]
        public async Task<ActionResult> Index(ListProfessionalViewModel view,int? page = null )
        {
            Session["professionalId"] = null;
            page = (page ?? 1);
            var profesionalViewModel = new List<ListProfessionalViewModel>();
            

            //var professionals = await ProfessionalBLL.GetAllProfessionals();
            var professionalType = ProfessionalBLL.GetAllProfessionalTypes();

            var listProfessionals = new List<Professional>();
            var roles = Helper.UserHelper.GetRolesByUser(User.Identity.GetUserName());

            if (roles.Where(rol => rol == "Súper_Administrador").FirstOrDefault() == "Súper_Administrador" ||
                roles.Where(rol => rol == "Administrador").FirstOrDefault() == "Administrador")
                profesionalViewModel = ProfessionalBLL.GetListProfessionals(null);
            else if (roles.Where(rol => rol == "Representantes").FirstOrDefault() == "Representantes")
            {
                var user = UserBLL.GetUserByUserName(User.Identity.GetUserName());
                profesionalViewModel = ProfessionalBLL.GetListProfessionals(user.Id).ToList();
            }
            if (!string.IsNullOrEmpty(view.FirstName))
            {
             var   profesionalViewMode = profesionalViewModel.Where(m => m.FullName.ToUpper().Contains(view.FirstName.ToUpper()));
                return View(profesionalViewMode.OrderBy(p => p.FullName).ToPagedList((int)page, 15));
            }


           else { 
                return View(profesionalViewModel.OrderBy(p => p.FullName).ToPagedList((int)page, 15));
            }
        }

        #region Creacion Profesionales

        [Authorize(Roles = "Súper_Administrador")]
        #region Profesionales
        public ActionResult Create()
        {
            var model = new ProfessionalViewModel
            {
                Professional = new Professional { Guid = Guid.NewGuid() },
                ProfessionalContact = new ProfessionalContact(),
                ProfessionalLaborInformation = new LaborInformation(),
            };
            return View(model);
        }

        [Authorize(Roles = "Súper_Administrador")]
        public ActionResult CreateProfessional()
        {
            var professionalType = ProfessionalBLL.GetAllProfessionalTypes();
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = new List<City>();
            var genders = GenderBLL.GetAllGender();
            var users = new List<User>();

            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name");
            ViewBag.CityId = new SelectList(cities, "Id", "Name");
            ViewBag.ProfessionalTypeId = new SelectList(professionalType, "Id", "Name");
            ViewBag.GenderId = new SelectList(genders, "Id", "Name");
            ViewBag.MsrId = new SelectList(users, "Id", "Name");

            var model = new Professional { Guid = Guid.NewGuid(), };
            return PartialView("~/Views/Professionals/_CreateProfessional.cshtml", model);
        }

        [Authorize(Roles = "Súper_Administrador")]
        [HttpPost]
        public ActionResult CreateProfessional(Professional model)
        {
            var response = new Response<ProfessionalContact>();
            if (Session["professionalId"] != null)
            {
                var professionalId = Convert.ToInt32(Session["professionalId"]);
                var professional = ProfessionalBLL.GetProfessionalById((int)professionalId);

                if (professional != null)
                {
                    var fail = new Response<bool>()
                    {
                        Result = false,
                        Model = false,
                        Message = "El profesional ya ha sido registrado.",
                        Title = "Administracion Profesionales"
                    };

                    return Json(fail);
                }
            }


            var professionalType = ProfessionalBLL.GetAllProfessionalTypes();
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = new List<City>();
            var genders = GenderBLL.GetAllGender();
            var users = new List<User>();

            ViewBag.DepartamentId = new SelectList(departaments, "Id", "Name", model.DepartamentId);
            ViewBag.CityId = new SelectList(cities, "Id", "Name", model.CityId);
            ViewBag.ProfessionalTypeId = new SelectList(professionalType, "Id", "Name", model.ProfessionalTypeId);
            ViewBag.GenderId = new SelectList(genders, "Id", "Name", model.GenderId);
            ViewBag.MsrId = new SelectList(users, "Id", "Name", model.MsrId);

            model.RegisterDate = DateTime.Now;
            // model.LastUpdate = DateTime.Now;
            model.Id = 0;

            if (model.MsrId != null && model.MsrId != 0)
                model.MsrMail = UserBLL.GetUserById((int)model.MsrId).Email;
            else
                ModelState.AddModelError(string.Empty, "El campo representante es requerido.");

            model.CreateBy = UserBLL.GetUserByUserName(User.Identity.GetUserName()).Id;

            try
            {
                model.BirthDate = (DateTime)ValidateDate(model.BirthDay,
                            model.BirthMonth, model.BirthYear);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "La fecha ingresada no es valida.");
            }

            if (model.DocumentNumber != null)
            {
                var objProfessional = ProfessionalBLL.GetProfessionalByDocumentNumber(Convert.ToString(model.DocumentNumber));

                if (objProfessional != null)
                    ModelState.AddModelError(string.Empty, "El numero de cédula ya se encuentra registrado.");
            }
            List<User> dataRepreSecundarios = new List<User>();

            if (model.RepresentantesSecundarios != null)
            {
                string[] ass = model.RepresentantesSecundarios.Split('|');
                
                if (ass != null && ass.FirstOrDefault() != "")
                {
                    //ViewBag.AssociatedProfessionals = convesion;

                    foreach (var item in ass)
                    {
                        if (item != "")
                        {
                            var data2 = UserBLL.GetUserByGuid(item);
                            dataRepreSecundarios.Add(data2);
                        }
                    }
                    ViewBag.RepresentantesSecundarios = new SelectList(dataRepreSecundarios, "Guid", "Name");
                }
            }

            if (ModelState.IsValid)
            {
                model.Token = Guid.NewGuid().ToString();
                var expirationDate = ConfigurationManager.AppSettings["Token.Expiration.Date"];
                model.ExpirationDateToken = Convert.ToDateTime(model.RegisterDate).AddDays(Convert.ToDouble(expirationDate));
                var professionalId = ProfessionalBLL.SaveNewProfessional(model);
                if (professionalId != null)
                {
                    Session["professionalId"] = professionalId;
                    var professionalContact = new ProfessionalContact()
                    {
                        Id = 0,
                        Guid = Guid.NewGuid(),
                        ProfessionalId = (int)professionalId
                    };

                    professionalContact.Id = (int)ProfessionalBLL.SaveProfessionalContact(professionalContact);
                    var nuevoProfesional = ProfessionalBLL.GetProfessionalById(professionalId.Value);
                    ProfessionalBLL.AsociateRepresentatsToProfessional(nuevoProfesional.Guid.ToString().ToUpper(), dataRepreSecundarios);

                    response = new Response<ProfessionalContact>()
                    {
                        Result = true,
                        Model = professionalContact,
                        Message = "El registro ha sido creado con éxito.",
                        Title = "Administracion Profesionales"
                    };
                }
            }
            else
            {
                response = new Response<ProfessionalContact>()
                {
                    Result = false,
                    Model = null,
                    Message = getModelError(ModelState.Values),
                    Title = "Administracion Profesionales"
                };
            }

            return Json(response);
        }
        #endregion

        #region Informacion de contacto
        [Authorize(Roles = "Súper_Administrador")]
        [HttpGet]
        public ActionResult ProfessionalContact()
        {
            var professionalId = Session["professionalId"];
            var professionalContact = new ProfessionalContact();
            var departaments = DepartamentBLL.GetAllDepartaments();
            var cities = new List<City>();

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Professionals/Create.cshtml
@model Big.MeadJohnson.Business.ViewModel.ProfessionalViewModel
@Styles.Render("~/Content/css")
<style>
    $body-bg : #eee; $canvas-bg: #fff; $font1 : Arial, sans-serif; body {
        background-color: $body-bg;
        font-family: $font1;
    }

    canvas {
        display: block;
        margin: 0 auto;
        margin: calc(50vh - 150px) auto 0;
        background: $canvas-bg;
        border-radius: 3px;
        box-shadow: 0px 0px 15px 3px #ccc;
        cursor: pointer;
    }

    p {
        text-align: center;
        cursor: pointer;
    }
</style>

@{
    ViewBag.Title = "Nuevo Profesional";
}
@Html.AntiForgeryToken()
<div class="container" style="background-color: #EEEEEE; opacity: 0.9; margin-top: 25px;">

    <div class="tabbable" style=" margin-top: 50px; margin-left: 25px; margin-right: 25px; border-bottom-width: 50px;">
        <div class="alert alert-warning" role="alert">
                <strong>Recuerda!</strong> Los campos marcados con ( * ) son obligatorios.
            </div>
        

        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">Profesional</a></li>
            <li><a href="#tab2" data-toggle="tab">Información de Contacto</a></li>
            <li><a href="#tab3" data-toggle="tab">Información Laboral</a></li>
            <li><a href="#tab4" data-toggle="tab">Información General</a></li>            
            <li><a href="#tab5"  data-toggle="tab">Información de Secretaria</a></li>
            <li><a href="#tab6"  data-toggle="tab">Firma</a></li>
            <li><a href="#tab7"  data-toggle="tab">Firma Secretaria </a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">

                @if (true)
                {
                    <div>
                        @{ Html.RenderAction("CreateProfessional", "Professionals");}
                    </div>
                }
            </div>
            <div class="tab-pane" id="tab2">
                <div>
                    @{ Html.RenderAction("ProfessionalContact", "Professionals");}
                </div>
            </div>
            <div class="tab-pane" id="tab3">
                <div>
                    @{ Html.RenderAction("LaborInformation", "Professionals");}
                </div>
            </div>
            <div class="tab-pane" id="tab4">
                <div>
                    @{ Html.RenderAction("GeneralInformation", "Professionals");}
                </div>
            </div>
            <div class="tab-pane" id="tab5">
                <div>
                    @{ Html.RenderAction("SecretaryInformation", "Professionals");}
                </div>
            </div>
            <div class="tab-pane" id="tab6">
                <div>
                    @{ Html.RenderAction("DigitalSignature", "Professionals");}
                </div>
            </div>
            <div class="tab-pane" id="tab7">
                @{ Html.RenderAction("DigitalSignatureSecretary", "Professionals");}
            </div>
        </div>
    </div>
</div>
<input type="hidden" name="imageData" id="imageData" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/canvas.js"></script>
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Professionals/Details.cshtml
@model Big.MeadJohnson.Business.Models.Professional

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Professional</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departament.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departament.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfessionalType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfessionalType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Guid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Guid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MsrMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MsrMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Professionals/Edit.cshtml
@model Big.MeadJohnson.Business.ViewModel.ProfessionalViewModel
@Styles.Render("~/Content/css")
<style>
    $body-bg : #eee; $canvas-bg: #fff; $font1 : Arial, sans-serif; body {
        background-color: $body-bg;
        font-family: $font1;
    }

    canvas {
        display: block;
        margin: 0 auto;
        margin: calc(50vh - 150px) auto 0;
        background: $canvas-bg;
        border-radius: 3px;
        box-shadow: 0px 0px 15px 3px #ccc;
        cursor: pointer;
    }

    p {
        text-align: center;
        cursor: pointer;
    }
</style>

@{
    ViewBag.Title = "Nuevo Profesional";
}

<div class="container" style="background-color: #EEEEEE; opacity: 0.9; margin-top: 25px;">
    @Html.AntiForgeryToken()
    <div class="tabbable" style="margin-top: 50px; margin-left: 25px; margin-right: 25px; border-bottom-width: 50px;">
        <div class="alert alert-warning" role="alert">
                <strong>Recuerda!</strong> Los campos marcados con ( * ) son obligatorios.
            </div>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab1" data-toggle="tab">Profesional</a></li>
            <li><a href="#tab2" data-toggle="tab">Información de Contacto</a></li>
            <li><a href="#tab3" data-toggle="tab">Información Laboral</a></li>
            <li><a href="#tab4" data-toggle="tab">Información General</a></li>
            @if (Model.Professional.ProfessionalTypeId != 4)
            {
            <li><a href="#tab5" data-toggle="tab">Información de Secretaria</a></li>
            }

            <li><a href="#tab6" data-toggle="tab">Firma</a></li>
            @if (Model.Professional.ProfessionalTypeId != 4)
            {

            <li><a href="#tab7" data-toggle="tab">Firma Secretaria</a></li>
            }

        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">

                @if (Model.Professional != null)
                {
                    <div>
                        @{ Html.RenderAction("EditProfessional", "Professionals", Model.Professional);}
                    </div>
                }
            </div>
            <div class="tab-pane" id="tab2">
                <div>
                    @{ Html.RenderAction("EditProfessionalContact", "Professionals", Model.ProfessionalContact);}
                </div>
            </div>
            <div class="tab-pane" id="tab3">
                <div>
                    @{ Html.RenderAction("EditLaborInformation", "Professionals", Model.ProfessionalLaborInformation);}
                </div>
            </div>
            <div class="tab-pane" id="tab4">
                <div>
                    @{ Html.RenderAction("EditGeneralInformation", "Professionals", Model.GeneralInformation);}
                </div>
            </div>
            @if (Model.Professional.ProfessionalTypeId != 4)
            {
                <div class="tab-pane" id="tab5">
                    <div>
                        @{ Html.RenderAction("EditSecretaryInformation", "Professionals", Model.SecretaryInformation);}
                    </div>
                </div>
             }
            
            <div class="tab-pane" id="tab6">
                <div>
                    <div>
                        @{ Html.RenderAction("EditDigitalSignature", "Professionals", Model.HabeasData);}
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="tab7">
               @{ Html.RenderAction("EditSecretaryDigitalSignature", "Professionals",Model.SecretaryHabeasData);}
            </div>
           
        </div>
    </div>
</div>
<input type="hidden" name="imageData" id="imageData" />
<input type="hidden" name="roleId" id="roleId"  value="@Model.RoleId "/>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/canvas.js"></script>
}



@*<script>
        var limpiar = document.getElementById("limpiar");
        var canvas = document.getElementById("canvas");
        var ctx = canvas.getContext("2d");
        var cw = canvas.width = 800,
            cx = cw / 2;
        var ch = canvas.height = 400,
            cy = ch / 2;

        var dibujar = false;
        var factorDeAlisamiento = 5;
        var Trazados = [];
        var puntos = [];
        ctx.lineJoin = "round";

        limpiar.addEventListener('click', function (evt) {
            dibujar = false;
            ctx.clearRect(0, 0, cw, ch);
            Trazados.length = 0;
            puntos.length = 0;
        }, false);


        canvas.addEventListener('mousedown', function (evt) {
            dibujar = true;
            //ctx.clearRect(0, 0, cw, ch);
            puntos.length = 0;
            ctx.beginPath();

        }, false);

        canvas.addEventListener('mouseup', function (evt) {
            redibujarTrazados();
        }, false);

        canvas.addEventListener("mouseout", function (evt) {
            redibujarTrazados();
        }, false);

        canvas.addEventListener("mousemove", function (evt) {
            if (dibujar) {
                var m = oMousePos(canvas, evt);
                puntos.push(m);
                ctx.lineTo(m.x, m.y);
                ctx.stroke();
            }
        }, false);





        function reducirArray(n, elArray) {
            var nuevoArray = [];
            nuevoArray[0] = elArray[0];
            for (var i = 0; i < elArray.length; i++) {
                if (i % n == 0) {
                    nuevoArray[nuevoArray.length] = elArray[i];
                }
            }
            nuevoArray[nuevoArray.length - 1] = elArray[elArray.length - 1];
            Trazados.push(nuevoArray);
        }

        function calcularPuntoDeControl(ry, a, b) {
            var pc = {}
            pc.x = (ry[a].x + ry[b].x) / 2;
            pc.y = (ry[a].y + ry[b].y) / 2;
            return pc;
        }

        function alisarTrazado(ry) {
            if (ry.length > 1) {
                var ultimoPunto = ry.length - 1;
                ctx.beginPath();
                ctx.moveTo(ry[0].x, ry[0].y);
                for (i = 1; i < ry.length - 2; i++) {
                    var pc = calcularPuntoDeControl(ry, i, i + 1);
                    ctx.quadraticCurveTo(ry[i].x, ry[i].y, pc.x, pc.y);
                }
                ctx.quadraticCurveTo(ry[ultimoPunto - 1].x, ry[ultimoPunto - 1].y, ry[ultimoPunto].x, ry[ultimoPunto].y);
                ctx.stroke();
            }
        }


        function redibujarTrazados() {
            dibujar = false;
            ctx.clearRect(0, 0, cw, ch);
            reducirArray(factorDeAlisamiento, puntos);
            for (var i = 0; i < Trazados.length; i++)
                alisarTrazado(Trazados[i]);
        }

        function oMousePos(canvas, evt) {
            var ClientRect = canvas.getBoundingClientRect();
            return { //objeto
                x: Math.round(evt.clientX - ClientRect.left),
                y: Math.round(evt.clientY - ClientRect.top)
            }
        }

    </script>*@

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Professionals/EditAnonymousProfessional.cshtml
@model Big.MeadJohnson.Business.ViewModel.EditProfessionalViewModel

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>
                &nbsp;
            </p>
        </div>
        <div class="col-md-12 hidden-xs">
            <p>
                &nbsp;
            </p>
        </div>
        <div class="col-md-12 hidden-xs">
            <p>
                &nbsp;
            </p>
        </div>
        <div class="login">
            <div class="col-md-5">
                <img src="~/Content/img/asset-2.png" class=" img-responsive" style="border-radius: 10px;" />
            </div>
            <div class="col-md-7">
                <br>
                @using (Html.BeginForm("EditAnonymousProfessional", "Professionals", null, FormMethod.Post))
                {

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.ProfessionalId)

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <strong style="font-size: 23px; color: #29408A;">
                        @Model.FullName
                    </strong>
                    <br>
                    <strong style="font-size: 39px; color: #29408A;">
                        ¡Juntos podremos nutrir de bienestar el futuro!
                    </strong>
                    <br>
                    <br>
                    <span style="font-size: 20px; color: #606060;">
                        Completa tu información personal para mantenerte actualizado con las noticias, beneficios e iniciativas que periódicamente construimos para ti.
                    </span>
                    <br>
                    <br>
                    <p>@Html.CheckBoxFor(model => model.CheckTerms)  @Html.LabelFor(model => model.CheckTerms)  <input type="submit" value="Aceptar" class="btn btn-primary pull-right" /></p>

                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>
                &nbsp;
            </p>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-6 text-center">
            <div class="login">
                <a href="~/Content/files/habeas.pdf" target="_blank" style="color: #29408A; font-size: 14px; font-weight: bold; text-decoration: underline;">Política del manejo de la información</a>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Big.MeadJohnson/Big.MeadJohnson.CRM.UI/Views/Professionals/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<Big.MeadJohnson.Business.ViewModel.ListProfessionalViewModel>

@{
    /**/

    ViewBag.Title = "Index";
}

<div class="container" style="background-color: #EEEEEE; opacity: 0.9; margin-top: 52px;">
    <h2>Profesionales</h2>
    @if (User.IsInRole("Súper_Administrador"))
    {
        <p>
            @Html.ActionLink("Nuevo Profesional", "Create", null, new { @class = "btn btn-primary" })
        </p>
    }
 
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-inline">

                <div class="col-md-10 ">
                    @*@Html.EditorFor(model => model.FirstOrDefault().FirstName, new { htmlAttributes = new { @class = "form-control cold-md-5 " } })*@
                    <input type="text" name="FirstName" id="FirstName" class="form-control cold-md-5" />
                    <input type="submit" value="Buscar" class="btn btn-success cold-md-5 " />
                </div>
            </div>
        }


        <table style="width:100%;" class="table dataTables_wrapper form-inline dt-bootstrap no-footer" id="dataTables-example">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().FullName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().ProfessionalTypeName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().LastUpdate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().PercentCompleteness)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
            {
                int progress = item.PercentCompleteness;
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProfessionalTypeName)
                        </td>
                        <td>
                          @{ 
                              if (item.LastUpdate != "")
                              {
                                  DateTime tmpDate = DateTime.ParseExact(item.LastUpdate, "dd/MM/yyyy", null);
                                  item.LastUpdate = tmpDate.ToString("yyyyMMdd");
                              }


                          }
                            
                            @Html.DisplayFor(modelItem => item.LastUpdate)
                        </td>
                        <td>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: @string.Format("{0}%", progress); ">
                                    <span class="sr-only">@string.Format("{0}% Complete", progress);</span>
                                    @string.Format("{0} %", progress)
                                </div>
                            </div>

                        </td>

                        <td>
                            @Html.ActionLink("Actualizar", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        Página: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber), de: @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
    PagedListRenderOptions.OnlyShowFivePagesAtATime);



</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

<link href="~/Content/PagedList.css" rel="stylesheet" />